apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-project
  labels:
    app: ci-project
spec:
  selector:
    matchLabels:
      app: ci-project
  replicas: 1
  template:
    metadata:
      name: ci-project
      labels:
        app: ci-project
    spec:
      containers:
        - name: ci-project
          image: local/ci-project:latest # Image that will be used inside the container in the cluster
          imagePullPolicy: Never
          ports:
           - containerPort: 8080 # The port that the container is running on in the cluster

---
apiVersion: v1
kind: Service
metadata:
  name: ci-project
  labels:
    app: ci-project
spec:
  type: NodePort
  selector:
    app: ci-project
  ports:
   - name: http
     port: 8080 # The port that the service is running on in the cluster
     targetPort: 8080